### ISSUE TITLE
Error: Failed to load gRPC binary module

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#100]
I'm having problem to run the `ding-dong-bot.js` script, which was used to be called `starter-bot.js`, which I didn't have problem running previously. Here is the error I'm getting now:

```
WECHATY_LOG=verbose node examples/ding-dong-bot.js
23:17:09 INFO Config registering process.on("unhandledRejection") for development/debug
23:17:09 VERB Config constructor()
23:17:09 ERR Config ###########################
23:17:09 ERR Config uncaughtException: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-linux-x64-glibc
Found: [node-v72-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/path/to/nodejs/wechaty-getting-started/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node' uncaughtException
23:17:09 ERR Config ###########################
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-linux-x64-glibc
Found: [node-v72-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/path/to/nodejs/wechaty-getting-started/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/path/to/nodejs/wechaty-getting-started/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

The readme at https://github.com/wechaty/wechaty-getting-started hasn't been updated to explain which new package need to be installed to make that working, I tried myself with the following as root, 

```
apt-get install libgrpc-dev
npm rebuild
```

But the problem remains. 

Please help. My system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

[question]

**Comment by huan** [comment]
I believe the repo should be OK because it can pass the CI without any problem.

See: <https://github.com/wechaty/wechaty-getting-started/runs/575771421>

Could you please try to `rm -fr node_modules && rm -f package-lock.json && npm i` and retry to see if it helps?

**Comment by suntong** [comment]
I just did, before I raised the issue. 

Having taken a closer look at the CI log, I believe I might have found the problem -- 

The CI's `node_modules` directory is _cached_, while mine is newly downloaded.  
The ding-dong-bot.js script was used to be called starter-bot.js, and I didn't have problem running it previously, before I did `rm -fr node_modules && rm -f package-lock.json && npm i`. 

Can you try doing `rm -fr node_modules && rm -f package-lock.json && npm i` at your side please?

**Comment by huan** [comment]
I did it twice and it works without any problem in my Ubuntu 19.10.

Cloud you try it in the CodeSandbox and to see if it could help you to figure out which part is causing the problem?

<https://codesandbox.io/s/github/wechaty/wechaty-getting-started/tree/master/?autoresize=1&fontsize=14&hidenavigation=1&module=%2Fexamples%2Fding-dong-bot.ts&theme=dark>

The above link will just check out the Github repo and run it. You can set up a new environment on CodeSandbox and try by yourself as well.

**Comment by suntong** [comment]
Oh, thanks a lot for checking it out for me. 

```
Expected directory: node-v64-linux-x64-glibc
Found: [node-v72-linux-x64-glibc]
```

That's what the actual cause is, according to https://stackoverflow.com/a/49758265/2125837
I.e., a version conflict which I believe most probably caused by me reverting from node 13 to node 10 -- https://github.com/wechaty/wechaty-puppet-padplus/issues/212. 

`npm rebuild` didn't solve the problem BTW, as explained in OP. 

I now think my node `v10.20.0` is not OK as I think, as wechaty-puppet-padplus@next _only_ supported `node@10.16.0`, as per @su-chang. 

Will try again tomorrow...

**Comment by suntong** [comment]
Hmmm, nope, node `v10.20.0` works well in CI -- https://travis-ci.com/github/wechaty/wechaty-getting-started/jobs/317990203.

Anyway, will check everything again tomorrow.

**Comment by huan** [comment]
In my Linux box with latest master branch code:

```
$ npm ls grpc wechaty wechaty-puppet wechaty-puppet-mock wechaty-puppet-puppeteer wechaty-puppet-padplus
wechaty-getting-started@0.2.7 /home/huan/chatie/wechaty-getting-started
└─┬ wechaty@0.38.4 
  ├── wechaty-puppet@0.24.0 
  └─┬ wechaty-puppet-hostie@0.6.1
    └─┬ @chatie/grpc@0.9.3
      └── grpc@1.24.2 
```

**Comment by suntong** [comment]
Oh, I'm terribly sorry to have caused you so much trouble.

- I thought it is just a harmless minor improvement.
- Obviously I don't know npm well enough
- I'll fix it for you. 
- You know you can re-triggle travis build without bumping up any version, right?

**Comment by suntong** [comment]
Question before jumping in fixing, 

The CI log at https://travis-ci.com/github/wechaty/wechaty-getting-started/jobs/317990203 shows that all `wechaty-puppet-mock`, `wechaty-puppet-puppeteer`, `wechaty-puppet-wechat4u`, and `wechaty-puppet-padplus` are being installed and tested.

Is it still the case now? --

- I didn't seem all of them in test logs now, although I didn't look too careful
- and if there are being installed (and tested), `npm ls` should have listed them, right?

**Comment by huan** [comment]
No problem, the repo is still good, it's just the CI tests failed.

For answering your questions:

1. We will test those puppets in CI, you can have a look at our smoke testing file at <https://github.com/wechaty/wechaty-getting-started/blob/master/tests/smoke-testing.js> for details.
1. Those npm modules will be installed during the smoke testing. However, because we did not save those dependencies in the package.json, so the next install will delete the previous install automatically by NPM, which means that you might only be able to see the latest tested one.

**Comment by suntong** [comment]
wechaty-puppet-puppeteer, and wechaty-puppet-padplus are no longer being tested. That's what I was caring. Thanks for confirmation -- I didn't remember wrong, :)

**Comment by suntong** [comment]
Please add them back, for the environments that they still work. I'll create a separated issue...

**Comment by suntong** [comment]
Finally fixed it, done a lot things, including `rm -rf ~/.cache/node-gyp/`, now I'm all good. 

Thanks again for all the helps!
