### ISSUE TITLE
微信被封号，想确认是哪个地方问题

### ISSUE THREAD

**Issue by 2017alan** [wechaty/wechaty-getting-started#114]
如图所以，我使用 wechaty-puppet-padplus 插件 登录 ipad 版本的微信。发现账号被封。
想确认是 个人微信问题，还是  程序问题。

使用的  wechaty    和 wechaty-puppet-padplus 都是最新版。
安装过程 参考了 https://github.com/wechaty/wechaty-puppet-padplus/blob/master/readme.md。
运行的是example 里面的 ding-dong-bot.js

######

![image](https://user-images.githubusercontent.com/32698401/79852174-ea0bee80-83f8-11ea-96b4-421904495edd.png)

**Comment by su-chang** [comment]
It depends on many cases:
1. When did the WeChat Account register?
2. What operations does the Bot do after login? 【**Important**】

    > e.g. send a lots of message during short time?

3. Before your account has been blocked, does the bot has been kicked off line forcibly or not?
4. Do you set `name` for Wechaty, in other words, do you need scan qrcode for login when each restart?

**Comment by 2017alan** [comment]
1. 微信号 前天注册的。
2. 没有做任何操作，登录上 ding-dong-bot.js 大概 10秒钟就挂了，我还没来得及反应。
3. 是的 ，先被 踢下线的。
4. 没有设置 name ,但我只登录了一次就挂了。【而且短期无法解封，很尴尬】

**Comment by su-chang** [comment]
Understand, it seems that this problem is due to the new account, your account is too new for login in third-part WeChat software.

Suggestions:
1. Get an account which has registered more than half year for login wechaty.
2. **DO NOT** do anything after login, keep it silent for 6 ~ 8 hours, and then you could awake your bot and do something.

**Comment by wxj1994** [comment]
Would you please use Chinese? When people ask questions in Chinese and you answer them in English, are you acting weird？

**Comment by huan** [comment]
Close this issue because the padplus has been deprecated.

Use [wechaty-puppet-padlocal](https://wechaty.js.org/docs/puppet-providers/padlocal/) instead.
