### ISSUE TITLE
发送图片 Demo please

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#129]
**Is your feature request related to a problem? Please describe.**
How to send an image from a file on disk to people/chart-room via wechaty?

I had the following in my code, which had been working fine before,

```js
 const fileBox = FileBox.fromFile(myFileName)
 await msg.say(fileBox)
```

but it ceased working since I don't know when. 
Maybe after I switched to wechaty-puppet-padplus?

**Describe the solution you'd like**
A simple demo would be appreciated.
Maybe just add another case to reply with an image in the ding-dong-bot.js or media-file-bot.js file, thanks.

[enhancement]

**Comment by huan** [comment]
If the above code does not work, then I believe it's a bug.

We have an example in Wechaty repo:

https://github.com/wechaty/wechaty/blob/70edb1d695c3a03e3b10edbb355f7acc753a8138/examples/ding-dong-bot.ts#L144-L150

**Comment by suntong** [comment]
Oh, thanks for your reply. 

Found the problem is my added `await msg.say(JSON.stringify(fileBox))`, which gave me:

```
(node:57222) UnhandledPromiseRejectionWarning: Error: FileBox.toJSON() can only work on limited FileBoxType(s). See: <https://github.com/huan/file-box/issues/25>
    at FileBox.toJSON (/.../nodejs/node_modules/file-box/dist/src/file-box.js:303:23)
    at JSON.stringify (<anonymous>)
```

It's just a plain `.png` file. Removing that line and things are working again. 
thx again!

**Comment by huan** [comment]
Glad to know you have fix it!

The rejection is because the read file is a async operation which can not be satisfied by the tojson call.
