### ISSUE TITLE
got vulnerabilities messages during installation 

### ISSUE THREAD

**Issue by gabriellliu** [wechaty/wechaty-getting-started#138]
fixed 8 of 12 vulnerabilities in 1021 scanned packages
  4 vulnerabilities required manual review and could not be updated
root@ubuntu-s-1vcpu-1gb-sfo3-01:~/wechaty-getting-started# npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.18.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty-puppet-wechat4u [dev]                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty-puppet-wechat4u > wechat4u > axios                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/880                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > in-gfw > mem                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1084                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > opencollective > minimist                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ npm-programmatic                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > npm-programmatic                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1507                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 4 vulnerabilities (2 low, 1 moderate, 1 critical) in 1022 scanned packages

How can I fix it?

**Comment by gabriellliu** [comment]
20:15:24 VERB PuppetPuppeteerBridge stop()
20:15:24 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
20:15:24 ERR PuppetPuppeteer start() exception: Error
Error: 
    at PuppetPuppeteer.<anonymous> (/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:446:32)
    at PuppetPuppeteer.emit (events.js:314:20)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:486:12)
    at PuppetPuppeteer.<anonymous> (/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:201:12)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:24:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
20:15:24 ERR Wechaty start() exception: 
20:15:24 ERR StarterBot Error
[nodemon] clean exit - waiting for changes before restar

**Comment by huan** [comment]
We have set up a Gitpod for Wechaty beginners to run Wechaty as soon as possible and as easily as possible.

Please read https://wechaty.github.io/wechaty-getting-started/docs/gitpod
