### ISSUE TITLE
npm ERR! wechaty-getting-started@0.4.59 start: `cross-env WECHATY_LOG=verbose node -r ts-node/register examples/ding-dong-bot.ts`

### ISSUE THREAD

**Issue by chenj-freedom** [wechaty/wechaty-getting-started#142]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
when I run the cmd 'npm start', I got the following error.

npm ERR! wechaty-getting-started@0.4.59 start: `cross-env WECHATY_LOG=verbose node -r ts-node/register examples/ding-dong-bot.ts`

**Comment by huan** [comment]
Are you using the win32 platform?

Did you run `npm install` before `npm start`?

**Comment by huan** [comment]
We have set up a Gitpod for Wechaty beginners to run Wechaty as soon as possible and as easily as possible.

Please read https://wechaty.github.io/wechaty-getting-started/docs/gitpod
