### ISSUE TITLE
ding-dong-bot.js example is not doing ding-dong handshaking

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#144]
## 2. Describe the bug

See
https://github.com/wechaty/wechaty-getting-started/blob/b6b918457c496d9d377d4e880bf08e8f405e2d84/examples/ding-dong-bot.js#L41

## 3. To Reproduce

1. run 'WECHATY_PUPPET=wechaty-puppet-puppeteer node ding-dong-bot.js'
2. send 'ding'

## 4. Expected behavior

Expected to receive "dong".

## 5. Actual behavior

Not receiving "dong", because there is no ding-dong handshaking logic.

https://github.com/wechaty/wechaty-getting-started/blob/b6b918457c496d9d377d4e880bf08e8f405e2d84/examples/ding-dong-bot.js#L40-L42

**Comment by huan** [comment]
Good catch!

We have the logic in the TS version:

https://github.com/wechaty/wechaty-getting-started/blob/b6b918457c496d9d377d4e880bf08e8f405e2d84/examples/ding-dong-bot.ts#L41-L47

But we missed this part of the code in the JS version.

Would you like to send a Pull Request to fix this issue?

**Comment by suntong** [comment]
ok, will do...
