### ISSUE TITLE
One page wechaty introduction

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty-getting-started#23]
Wechaty changes a lot these days and maybe we should make a clear tutorial, one-page introduction and API doc these days, both support Chinese and English.

Thanks to https://github.com/Chatie/wechaty-getting-started/issues/19#issuecomment-401602671 pointing that the docs and tutorial make developer feel confusing and all his experience.

I write related todo list on scratch:

### First Priority
- [x] Wechaty-getting-started
  - [x] What wechaty do, what the project is trying to fix the problem.
  - [x] How to run the project, warning that for new accounts it may not works.
  - [x] Chinese version
  - [x] English version
- [x] Example code
  ~~- [ ] ding-dong-bot~~
  ~~- [ ] room-bot~~
  - [x] contact-bot
  - [x] media-file-bot
  - [x] starter-bot
  - [x] tuling123-bot
  - [x] vedio-demo
- [x] wechaty API doc
  - [x] Rewrite jsdoc https://github.com/Chatie/wechaty/pull/1458
  - [x] Using [docsify](https://docsify.js.org/#/) to generate API page : https://github.com/qhduan/wechaty-doc
  - [x] Chinese version
  - [x] English version
- [x] FAQ
  - [x] Why puppeteer is no more working for new accounts
  - [x] How to test the new version of wechaty
  - [x] What to do for new accounts

### Seconde Priority
- [ ] one-page introduction
  - [ ] getting-started
  - [ ] tutorial
  - [ ] blog
- [ ] Blog
 - [ ] Related practice from other developers & blog
 - [ ] What is the best practice about the project
 - [ ] Blog template
 - [ ] Author stories: About the project background
- [ ] Best practice
    - [ ] How to migrate from puppeteer(0.14) to padchat(0.18)

This Two part should move to wechaty repo instead of in wechaty-getting started.
- [ ]  Explanation of related concepts, including puppet, puppeteer, padchat, etc
  - [ ] Puppet System
  - [ ] Wechaty-puppet-padchat
  - [ ] Wechaty-puppet-puppeteer
  - [ ] hostie
  - [ ] giftie
  - [ ] botie
- [ ] Wechaty Introduction
  - [ ] How the whole project works

**Comment by lijiarui** [comment]
We have done all First Priority things and the others are the enhancement part, will keep it open when we finish the enhancement part until having a clear though.

Also, we have some bugs about the basic introduction, I will file a new one and we are trying to fix them as soon as possible.

**Comment by lijiarui** [comment]
Only left #17

**Comment by lijiarui** [comment]
Yes, I want to make it open. And will do the `Second Priority ` things in the next month.

**Comment by lijiarui** [comment]
Yes, I want to make it open. And will do the `Second Priority ` things in the next month.

**Comment by zixia** [comment]
Ok. So please update it in time and keep track on it until to can be closed.

Thank you very much.

**Comment by huan** [comment]
I'll close this issue because there have another 12 months passed.
