### ISSUE TITLE
image cannot be send

### ISSUE THREAD

**Issue by tianshunjian** [wechaty/wechaty-getting-started#60]
I run the starter-bot.js, and onMessage as below. However, when I receive a message, "hello" can be send successfully everytime, but the image can not send. I do not understand why
```
async function onMessage (msg) {
  console.log(msg.toString())
    if (!msg.self()){
        await msg.say('hello')
        const fileBox = FileBox.fromFile('./img/tuzi.png')
        await msg.say(fileBox)
    }
}
```

**Comment by zixia** [comment]
Had you tried to use a '.jpg' instead of a '.png'?

**Comment by huan** [comment]
Maybe duplicated with https://github.com/Chatie/wechaty-puppet-puppeteer/issues/91
