### ISSUE TITLE
Automatic re-login gone?

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#69]
I was able to resume login without scanning the qrcode again during my previous testings, even without specifying a profile, which _"will generate a file called wechatyName.memory-card.json.  This file stores the bot’s login information.  If the file is valid, the bot can auto login so you don’t need to scan the qrcode to login again. "_ according to the API Doc. 

but now it seems not working anymore -- I always have to scan the qrcode to login again. 

Tried with the default `starter-bot.js` and the `hot-import-bot.js` (https://github.com/wechaty/wechaty-getting-started/tree/master/examples/professional/hot-import-bot), and both are the same. 

Hope the two files can be corrected to show how the automatic re-login can be done. 
Thx.

**Comment by huan** [comment]
The starter-bot should work now, so I will close this issue.

Please feel free to let me know if there's any problem related to automatic re-login.

BTW: the `profile` in options was deprecated. it had been renamed to `name`.
