### ISSUE TITLE
配置完了token环境变量，运行npm start报错

### ISSUE THREAD

**Issue by nihaodanse** [wechaty/wechaty-getting-started#73]
PS F:\ayzb\we\wechaty-getting-started>  npm start

> wechaty-getting-started@0.1.0 start F:\ayzb\we\wechaty-getting-started
> node examples/starter-bot.js

14:30:19 INFO Wechaty <wechaty_puppet> start() v0.22.6 is starting...
14:30:19 INFO PuppetManager install(wechaty_puppet@latest) please wait ...
npm: npm
npm: ERR! code E404
npm ERR! 404
npm:  Not Found: wechaty_puppet@latest

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T06_30_24_611Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T06_30_24_611Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
14:30:24 ERR Wechaty start() exception: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T06_30_24_611Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T06_30_24_611Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
PS F:\ayzb\we\wechaty-getting-started>

**Comment by windmemory** [comment]
npm用的不是官方的源吧

**Comment by nihaodanse** [comment]
> npm用的不是官方的源吧

PS F:\ayzb\we\wechaty-getting-started> npm install

> wechaty-getting-started@0.1.0 postinstall F:\ayzb\we\wechaty-getting-started
> check-node-version --node ">= 10"

npm WARN wechaty-puppet-padchat@0.18.2 requires a peer of wechaty-puppet@^0.15.6 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-padpro@0.0.50 requires a peer of wechaty-puppet@^0.15.1 but none is installed. You must install peer dependencies yourself.

audited 2007 packages in 3.052s
found 0 vulnerabilities

PS F:\ayzb\we\wechaty-getting-started> npm install wechaty-puppet-padchat
npm WARN wechaty-puppet-padpro@0.0.50 requires a peer of wechaty-puppet@^0.15.1 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-padchat@0.18.2 requires a peer of wechaty-puppet@^0.15.6 but none is installed. You must install peer dependencies yourself.

+ wechaty-puppet-padchat@0.18.2
updated 1 package and audited 2007 packages in 5.366s
found 0 vulnerabilities

PS F:\ayzb\we\wechaty-getting-started>

**Comment by windmemory** [comment]
从这个log看，是安装成功了

**Comment by nihaodanse** [comment]
> 从这个日志看，是安装成功了

但是在npm start的时候依然报这个错是什么原因 环境变量也配置了

PS F:\ayzb\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start F:\ayzb\we\wechaty-getting-started
> node examples/starter-bot.js

18:13:22 INFO Wechaty <wechaty_puppet> start() v0.22.6 is starting...
18:13:22 INFO PuppetManager install(wechaty_puppet@latest) please wait ...
npm: npm
npm: ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm:
npm
npm:  ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T10_13_26_357Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T10_13_26_357Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
18:13:26 ERR Wechaty start() exception: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T10_13_26_357Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-27T10_13_26_357Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
PS F:\ayzb\we\wechaty-getting-started>

**Comment by nihaodanse** [comment]
> 从这个log看，是安装成功了

但是在npm start的时候依然报这个错是什么原因环境变量也配置了

PS F：\ ayzb \ we \ wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0启动F：\ ayzb \ we \ wechaty-getting-started 
> 节点示例/ starter-bot.js

18:13:22 INFO Wechaty <wechaty_puppet> start（）v0.22.6即将开始... 
18:13:22 INFO PuppetManager安装（wechaty_puppet @ latest）请稍等... 
npm：npm 
npm：ERR！代码E404 
npm ERR！找不到404：wechaty_puppet @ latest

npm：
npm 
npm：ERR！可以在以下位置找到此运行的完整日志：
npm ERR！d：\开发\的NodeJS \ node_cache_logs \ 2019-02-27T10_13_26_357Z-的debug.log

{错误：命令失败：npm install wechaty_puppet @ latest 
npm ERR！代码E404 
npm ERR！找不到404：wechaty_puppet @ latest

错误的ERR！可以在以下位置找到此运行的完整日志：
npm ERR！d：\开发\的NodeJS \ node_cache_logs \ 2019-02-27T10_13_26_357Z-的debug.log

```
at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.EventEmitter.emit (domain.js:441:20)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
kill ：false，
代码：1，
signal：null，
cmd：'npm install wechaty_puppet @ latest'} 
18:13:26 ERR Wechaty start（）异常：命令失败：npm install wechaty_puppet @ latest 
npm ERR！代码E404 
npm ERR！找不到404：wechaty_puppet @ latest

错误的ERR！可以在以下位置找到此运行的完整日志：
npm ERR！d：\开发\的NodeJS \ node_cache_logs \ 2019-02-27T10_13_26_357Z-的debug.log

{错误：命令失败：npm install wechaty_puppet @ latest 
npm ERR！代码E404 
npm ERR！找不到404：wechaty_puppet @ latest

错误的ERR！可以在以下位置找到此运行的完整日志：
npm ERR！d：\开发\的NodeJS \ node_cache_logs \ 2019-02-27T10_13_26_357Z-的debug.log

```
at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.EventEmitter.emit (domain.js:441:20)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
kill ：false，
代码：1，
signal：null，
cmd：'npm install wechaty_puppet @ latest'} 
PS F：\ ayzb \ we \ wechaty-getting-started>

**Comment by lijiarui** [comment]
Please try the following command
```shell
rm -rf package-lock.json
rm -rf node_modules
npm install wechaty
npm instal wechaty-puppet-padchat@next
npm start
```

**Comment by huan** [comment]
Duplicated with #76
