### ISSUE TITLE
npm start时报错

### ISSUE THREAD

**Issue by WU147258369** [wechaty/wechaty-getting-started#74]
PS H:\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start H:\we\wechaty-getting-started
> node examples/starter-bot.js

18:40:57 INFO Wechaty <padchat npm start> start() v0.22.6 is starting...
18:40:57 INFO PuppetManager install(padchat npm start@latest) please wait ...
npm: npm
npm:  WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start

npm: npm
npm:  ERR! code E404

npm: npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm
npm:  ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-27T10_41_02_904Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-27T10_41_02_904Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }
18:41:02 ERR Wechaty start() exception: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-27T10_41_02_904Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-27T10_41_02_904Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }

**Comment by windmemory** [comment]
> { Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404 'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

报错信息说的很清楚，找不到padchat这个包，包名错误

我们的包叫做`wechaty-puppet-padchat`

**Comment by lijiarui** [comment]
Please try the following command
```shell
rm -rf package-lock.json
rm -rf node_modules
npm install wechaty
npm instal wechaty-puppet-padchat@next
npm start
```

**Comment by WU147258369** [comment]
> 请尝试以下命令
> 
> ```shell
> rm -rf package-lock.json
> rm -rf node_modules
> npm install wechaty
> npm安装wechaty-puppet-padchat @ next
> npm开始
> ```
还是不行依然报这个错误

**Comment by WU147258369** [comment]
> > {错误：命令失败：npm install padchat npm start @ latest 
> > npm WARN不赞成使用start@5.1.0：不赞成使用https://github.com/deepsweet/start 
> > npm ERR！代码E404 
> > npm ERR！404 Not Found  -  GET https://registry.npmjs.org/padchat - 未找到
> > npm ERR！404 
> > npm ERR！404'padchat @ latest'不在npm注册表中。
> > 错误的ERR！404您的包名无效，因为
> > npm ERR！404 1.名称只能包含URL友好的字符
> > npm ERR！404 
> > npm ERR！404请注意，您也可以从
> > npm ERR 安装！404 tarball，文件夹，http url或git url。
> 
> 报错信息说的很清楚，找不到padchat这个包，包名错误
> 
> 我们的包叫做`wechaty-puppet-padchat`

包名都改了，还是不行

**Comment by windmemory** [comment]
这里显示了你运行的指令，是这个
```
npm install padchat npm start@latest
```
这个指令明显有问题，应该是你自己写的吧，请学习npm的相关指令，然后再尝试启动

**Comment by lijiarui** [comment]
@WU147258369 Please paste the full  command line and related full log

**Comment by WU147258369** [comment]
> @ WU147258369请粘贴完整的命令行和相关的完整日志

PS H:\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start H:\we\wechaty-getting-started
> node examples/starter-bot.js

16:12:44 INFO Wechaty <padchat npm start> start() v0.22.6 is starting...
16:12:44 INFO PuppetManager install(padchat npm start@latest) please wait ...
npm: npm
npm:  WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start

npm: npm
npm:  ERR! code E404

npm: npm
npm:  ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.

npm: npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404
npm:  tarball, folder, http url, or git url.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:600:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }
16:12:53 ERR Wechaty start() exception: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:600:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }

**Comment by WU147258369** [comment]
> 有问题，应该是你自己写的吧，请学习npm的相关指令，然后再尝试启动

PS H:\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start H:\we\wechaty-getting-started
> node examples/starter-bot.js

16:12:44 INFO Wechaty <padchat npm start> start() v0.22.6 is starting...
16:12:44 INFO PuppetManager install(padchat npm start@latest) please wait ...
npm: npm
npm:  WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start

npm: npm
npm:  ERR! code E404

npm: npm
npm:  ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.

npm: npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404
npm:  tarball, folder, http url, or git url.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:600:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }
16:12:53 ERR Wechaty start() exception: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T08_12_53_750Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:600:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }

**Comment by lijiarui** [comment]
请粘贴完整的日志，每一条命令后面带着一个日志。

看起来你安装的是`padchat` 包，而我们需要的是  `wechaty-puppet-padchat` 包。

你可以删除node_modules 文件夹和 package-lock.json 文件，重新安装试一试。

有问题的话，记得带着每个命令行和下面的日志发在这

```shell
rm -rf package-lock.json   // 删除文件
rm -rf node_modules        // 删除文件夹
npm install wechaty       // 安装 wechaty
npm instal wechaty-puppet-padchat@next // 安装 wechaty-puppet-padchat
npm start // 启动
```

**Comment by WU147258369** [comment]
> 请粘贴完整的日志，每一条命令后面带着一个日志。
> 
> 看起来你安装的是`padchat` 包，而我们需要的是 `wechaty-puppet-padchat` 包。
> 
> 你可以删除node_modules 文件夹和 package-lock.json 文件，重新安装试一试。
> 
> 有问题的话，记得带着每个命令行和下面的日志发在这
> 
> ```shell
> rm -rf package-lock.json   // 删除文件
> rm -rf node_modules        // 删除文件夹
> npm install wechaty       // 安装 wechaty
> npm instal wechaty-puppet-padchat@next // 安装 wechaty-puppet-padchat
> npm start // 启动
> ```
S H:\we\wechaty-getting-started> rm -rf package-lock.json
Remove-Item : 找不到与参数名称“rf”匹配的参数。
所在位置 行:1 字符: 4
+ rm -rf package-lock.json
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
PS H:\we\wechaty-getting-started> rm -rf node_modules
Remove-Item : 找不到与参数名称“rf”匹配的参数。
所在位置 行:1 字符: 4
+ rm -rf node_modules
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
PS H:\we\wechaty-getting-started> npm install wechaty
npm WARN wechaty-puppet-padchat@0.18.2 requires a peer of wechaty-puppet@^0.15.6 but none is installed. You must install peer dependencies yourself.

+ wechaty@0.22.6
updated 1 package and audited 864 packages in 14.189s
found 0 vulnerabilities

PS H:\we\wechaty-getting-started> npm instal wechaty-puppet-padchat@next

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\Admin\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.8.0 C:\Users\Admin\AppData\Roaming\npm\node_modules\npm

Did you mean one of these?
    install
    unstar
    init
PS H:\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start H:\we\wechaty-getting-started
> node examples/starter-bot.js

18:08:24 INFO Wechaty <padchat npm start> start() v0.22.6 is starting...
18:08:24 INFO PuppetManager install(padchat npm start@latest) please wait ...
npm: npm
npm:  WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start

npm: npm
npm:  ERR! code E404

npm: npm
npm:  ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because

npm: npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T10_08_28_334Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T10_08_28_334Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }
18:08:28 ERR Wechaty start() exception: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T10_08_28_334Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-04T10_08_28_334Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }

**Comment by lijiarui** [comment]
windows 系统下，你手工删除package-lock.json   和 node_modules 吧，我的命令是linux 下的命令。你这两个命令没有执行成功

**Comment by WU147258369** [comment]
> windows 系统下，你手工删除package-lock.json 和 node_modules 吧，我的命令是linux 下的命令。你这两个命令没有执行成功

但是我手动删除结果应该一样吧，后面二条命令报错咋解决

**Comment by lijiarui** [comment]
你先解决第一个。

**Comment by huan** [comment]
Close this issue due to no activities for more than 3 months.
