### ISSUE TITLE
全部都安装上了 一直说找不到 npm: ERR! 404 Not Found: wechaty_puppet@latest 

### ISSUE THREAD

**Issue by nihaodanse** [wechaty/wechaty-getting-started#76]
PS F:\ayzb\wechaty-puppet-padchat> npm start

> wechaty-getting-started@0.1.0 start F:\ayzb\wechaty-puppet-padchat
> node examples/starter-bot.js

15:20:01 INFO Wechaty <wechaty_puppet> start() v0.22.6 is starting...
15:20:01 INFO PuppetManager install(wechaty_puppet@latest) please wait ...
npm: npm
npm:  ERR! code E404
npm
npm: ERR! 404 Not Found: wechaty_puppet@latest

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-28T07_20_09_908Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-28T07_20_09_908Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
15:20:10 ERR Wechaty start() exception: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-28T07_20_09_908Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-02-28T07_20_09_908Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
PS F:\ayzb\wechaty-puppet-padchat>

**Comment by lijiarui** [comment]
Could you describe your issue as the following template? Thanks!

----

> Important：Please file the issue follow the template, or we won't help you to solve the problem.


## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Steps to reproduce the behavior:
1. run '...'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.


## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context
Add any other context about the problem here.

[bug]

**Comment by lijiarui** [comment]
Try the following command

```shell
rm -rf package-lock.json
rm -rf node_modules
npm install wechaty
npm instal wechaty-puppet-padchat@next
npm start
```

**Comment by nihaodanse** [comment]
> 请尝试以下命令
> 
> ```shell
> rm -rf package-lock.json 
> rm -rf node_modules 
> npm install wechaty 
> npm instal wechaty-puppet-padchat @ next 
> npm start
> ```
以上命令解决不了问题
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS F:\ayzb\wechaty-puppet-padchat> rm -rf package-lock.json
Remove-Item : 找不到与参数名称“rf”匹配的参数。
所在位置 行:1 字符: 4
+ rm -rf package-lock.json
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
PS F:\ayzb\wechaty-puppet-padchat> rm -rf node_modules
Remove-Item : 找不到与参数名称“rf”匹配的参数。
所在位置 行:1 字符: 4
+ rm -rf node_modules
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
PS F:\ayzb\wechaty-puppet-padchat>

**Comment by lijiarui** [comment]
Please delete file `package-lock.json` and folder `node_modules`

**Comment by nihaodanse** [comment]
> Please delete file `package-lock.json` and folder `node_modules`. Then try again.

每一步都按照你说的做的，还是这个log，能帮忙看一下吗

PS F:\ayzb\we2\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start F:\ayzb\we2\wechaty-getting-started
> node examples/starter-bot.js

15:07:43 INFO Wechaty <wechaty_puppet> start() v0.22.6 is starting...
15:07:43 INFO PuppetManager install(wechaty_puppet@latest) please wait ...
npm: npm
npm: ERR! code E404
npm
npm:  ERR! 404 Not Found: wechaty_puppet@latest

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-03-04T07_07_46_081Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-03-04T07_07_46_081Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
15:07:46 ERR Wechaty start() exception: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-03-04T07_07_46_081Z-debug.log

{ Error: Command failed: npm install wechaty_puppet@latest
npm ERR! code E404
npm ERR! 404 Not Found: wechaty_puppet@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2019-03-04T07_07_46_081Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty_puppet@latest ' }
PS F:\ayzb\we2\wechaty-getting-started>

**Comment by lijiarui** [comment]
1. 删除 `package-lock.json` 和 `node_modules`
2. 安装 wechaty
3. 安装 wechaty-puppet-padchat

**Comment by nihaodanse** [comment]
> 1. 删除 `package-lock.json` 和 `node_modules`
> 2. 安装 wechaty
> 3. 安装 wechaty-puppet-padchat

你好 我就是按照你说的做的 先删除`package-lock.json` 和 `node_modules`
然后npm install wechaty
接着npm install wechaty-puppet-padchat
最后npm start

还是报的上面的错 环境变量也配置了

**Comment by lijiarui** [comment]
你可以重新创建个目录，然后每一步按照我的操作，都附上相关的日志么？ 每操作一步，放一步日志。

**Comment by zh1314** [comment]
楼主解决了吗，我也是同样的问题

**Comment by huan** [comment]
It should not be `wechaty_puppet`, but `wechaty-puppet-puppeteer`, or `wechaty-puppet-padpro`, etc.

Learn more from: <https://github.com/Chatie/wechaty-puppet/wiki/Directory>
