### ISSUE TITLE
npm start 运行时报错

### ISSUE THREAD

**Issue by WU147258369** [wechaty/wechaty-getting-started#77]
🚨 The issue tracker is not for questions 🚨

1.你的wechaty版本是什么？
  回答：通过这个命令npm install wechaty-puppet-padchat直接获取的
 2.你用的是哪个傀儡？（padchat / puppeteer / padpro / ...）
  答案：padchat
3. 什么是你的wechaty-puppet-XXX（padchat / puppeteer /）版本？
  回答：padchat
4. 你的节点版本是什么？（运行`node --version`）
  答案：node
 5.您使用的是什么操作系统
  答案：window
6.预期的行为
 答案：登录微信获取消息
7.日志输出
PS H:\we\wechaty-getting-started> npm start

> wechaty-getting-started@0.1.0 start H:\we\wechaty-getting-started
> node examples/starter-bot.js

18:27:56 INFO Wechaty <padchat npm start> start() v0.22.6 is starting...
18:27:56 INFO PuppetManager install(padchat npm start@latest) please wait ...
npm: npm
npm:  WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start

npm: npm
npm:  ERR! code E404

npm: npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-28T10_28_00_966Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-28T10_28_00_966Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }
18:28:01 ERR Wechaty start() exception: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-28T10_28_00_966Z-debug.log

{ Error: Command failed: npm install padchat npm start@latest
npm WARN deprecated start@5.1.0: Deprecated in favor of https://github.com/deepsweet/start
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/padchat - Not found
npm ERR! 404
npm ERR! 404  'padchat@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-02-28T10_28_00_966Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install padchat npm start@latest ' }

**Comment by lijiarui** [comment]
Try the following command:

```shel
rm -rf package-lock.json
rm -rf node_modules
npm install wechaty
npm instal wechaty-puppet-padchat
npm start
```

**Comment by zh1314** [comment]
楼主解决了吗，我也是同样的问题

**Comment by huan** [comment]
Duplicated with #76
