### ISSUE TITLE
用node example/starter-bot.js在macbook上运行的时候报错。请问如何解决？

### ISSUE THREAD

**Issue by frankgo81** [wechaty/wechaty-getting-started#78]
用node example/starter-bot.js在macbook上运行的时候报错。请问如何解决？

------——————————————————————————————

fuxs-MacBook-Pro:wechaty frankgo$ node examples/starter-bot.js
19:24:44 INFO Wechaty <default> start() v0.22.6 is starting...
19:24:44 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.14.1) please wait ...
npm: npm
npm:  WARN checkPermissions Missing write access to /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules

npm: npm
npm:  WARN rx-queue@0.6.2 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm: npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.

npm: npm
npm:  WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.

npm: 

npm: npm
npm:  ERR! path /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules

npm: npm
npm:  
npm: ERR!
npm:  
npm: code
npm:  EACCES

npm: npm
npm:  
npm: ERR!
npm:  
npm: errno
npm:  -13

npm: npm
npm:  
npm: ERR!
npm:  
npm: syscall
npm:  access

npm: npm
npm:  
npm: ERR!
npm:  Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules'

npm: npm
npm:  ERR!
npm:   { [Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules']
npm ERR!   stack:

npm: npm ERR!    'Error: EACCES: permission denied, access \'/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules\'',

npm: npm ERR!   errno: -13,
npm ERR!
npm:    code: 'EACCES',
npm ERR!
npm:    syscall: 'access',
npm ERR!
npm:    path:

npm: npm ERR!    '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules' }

npm: npm
npm:  ERR! 

npm: npm
npm:  ERR!
npm:  The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user

npm: npm ERR! 
npm ERR!
npm:  If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running

npm: npm ERR! the command again as root/Administrator (though this is not recommended).

npm: 

npm: npm
npm:  ERR! A complete log of this run can be found in:
npm 
npm: ERR!
npm:      /Users/frankgo/.npm/_logs/2019-03-03T11_24_46_996Z-debug.log

{ Error: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1 
npm WARN checkPermissions Missing write access to /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm WARN rx-queue@0.6.2 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frankgo/.npm/_logs/2019-03-03T11_24_46_996Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm install wechaty-puppet-puppeteer@^0.14.1 ' }
19:24:47 ERR Wechaty start() exception: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1 
npm WARN checkPermissions Missing write access to /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm WARN rx-queue@0.6.2 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frankgo/.npm/_logs/2019-03-03T11_24_46_996Z-debug.log

{ Error: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1 
npm WARN checkPermissions Missing write access to /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm WARN rx-queue@0.6.2 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.6 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/Users/frankgo/Developer/wechaty/node_modules/wechaty/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frankgo/.npm/_logs/2019-03-03T11_24_46_996Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm install wechaty-puppet-puppeteer@^0.14.1 ' }
fuxiaos-MacBook-Pro:wechaty frankgo$ fuxiao node examples/starter-bot.js
-bash: fuxiao: command not found
fuxiaos-MacBook-Pro:wechaty frankgo$ root node examples/starter-bot.js
-bash: root: command not found

**Comment by frankgo81** [comment]
Problem solved...first you need to disable VPN service and then use:

"sudo npm install --save  wechaty-puppet-puppeteer@^0.14.1   --unsafe-perm=true" to fix the access permission problem..before running npm start!!

**Comment by lijiarui** [comment]
Cool， then could you help me to close this issue if there aren't any questions?

**Comment by frankgo81** [comment]
sure..let me close it nwo..thanks.
