### ISSUE TITLE
gist-bot/  将不同的处理模块分散到不同文件里面的代码例子，运行后报错

### ISSUE THREAD

**Issue by god-bless-me** [wechaty/wechaty-getting-started#80]
1.你的wechaty版本是什么？
回答：通过这个命令npm install wechaty-puppet-padchat直接获取的
2.你用的是哪个傀儡？（padchat / puppeteer / padpro / ...）
答案：padchat
3. 什么是你的wechaty-puppet-XXX（padchat / puppeteer /）版本？
回答：padchat
4. 你的节点版本是什么？（运行node --version）
答案：node 10.15.1
5.您使用的是什么操作系统
答案：window7
6.预期的行为
答案：测试gist-bot/将不同的处理模块分散到不同文件里面的代码例子
7.日志输出
![image](https://user-images.githubusercontent.com/13415085/53715702-9bfef900-3e8d-11e9-91c2-a7cd983b2700.png)

**Comment by lijiarui** [comment]
please follow the template as https://github.com/lijiarui/wechaty-puppet-padchat/issues/253#issuecomment-469138339 shown
