### ISSUE TITLE
TypeError: state_switch_1.default is not a constructor

### ISSUE THREAD

**Issue by gengchen528** [wechaty/wechaty-getting-started#83]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

今天这个问题出现在好多版本上，不知道是出了什么问题，拉的是这个项目最新的代码
![image](https://user-images.githubusercontent.com/20028566/59962060-f42c3a80-9512-11e9-99b4-b2fdf08f00a7.png)

**Comment by huan** [comment]
Please don't put the master branch unless you can read the source code and have the willing to dig into it and fix it if there's any problem, because the master branch is not stable for users.

Use the latest version from npm by run `npm install wechaty@latest` instead.

**Comment by gengchen528** [comment]
ok  thanks

**Comment by gengchen528** [comment]
but when i use latest instead , it also has this problem. i have removed lock file. only use wecahty .wechaty version is 0.26.1
![image](https://user-images.githubusercontent.com/20028566/59962251-64d45680-9515-11e9-9dd0-6f428cdaad42.png)

**Comment by huan** [comment]
Ok, it seems that there have some problems with the state-switch module.

Will look into it later.

**Comment by huan** [comment]
Could you please change the issue title to the error message start with the TypeError ? Because that will make the problem more clear.

**Comment by huan** [comment]
@gengchen528 Thank you for reporting this.

This bug was confirmed and it was introduced from the upgrade of `state-switch` module.

Now the bug was killed and please test and free to let me know if there have any other problems.

**Comment by gengchen528** [comment]
ok   thank you.
