### ISSUE TITLE
The wechaty version is too old

### ISSUE THREAD

**Issue by sannere** [wechaty/wechaty-getting-started#84]
I found that the version of `wechaty` in the package.json is `0.22.6`, but the latest version of `wechaty` is `0.27.x`, please upgrade the `wechaty` to latest version so developers could use the latest version from this template.

**Comment by huan** [comment]
Thanks for your kindly notice, but you are outdated. ;-)

Please see the latest master branch of this repo, we are using 0.27.36 right now.

https://github.com/wechaty/wechaty-getting-started/blob/153532808eee5a50e3c7e39150f265b500554f63/package.json#L30

You need a `git pull` to update your local files.

**Comment by huan** [comment]
And please pay attention to our version number that:

1. v0.27 is not the `latest` version, it's the `next` version, which means it's in developing, and might not be stable.
1. v0.26 is our `latest` version which should be more predictable and stable.

**Comment by huan** [comment]
Close this issue due to no activities for 60 days.
